# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-23 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barreauproject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='formateur',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Formateur',
        ),
    ]
