# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-29 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barreauproject', '0007_delete_nbreheureformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='url_site_web',
            field=models.CharField(default='https://', max_length=200),
        ),
    ]
