# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-29 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barreauproject', '0008_partenaire_url_site_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
