# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-29 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barreauproject', '0009_partenaire_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partenaire',
            options={'ordering': ['nom']},
        ),
        migrations.RenameField(
            model_name='dateideb',
            old_name='date',
            new_name='date_en_francais',
        ),
    ]
