# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-30 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0004_formateur_statut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='long_description',
            new_name='contenu',
        ),
        migrations.AddField(
            model_name='event',
            name='infos_pratiques',
            field=models.TextField(blank=True, null=True),
        ),
    ]
