# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-30 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0005_auto_20180130_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formateur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='mes_images/'),
        ),
        migrations.AlterField(
            model_name='formateur',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
