# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-23 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barreauproject', '0003_newsletteremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='membre',
            name='url_site_web',
            field=models.CharField(default='https://', max_length=200),
        ),
        migrations.AlterField(
            model_name='photogallerie',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barreauproject.Categorie'),
        ),
    ]
